### ISSUE TITLE
AttributeError in Discoverer.__init__ method when using Windows

### ISSUE THREAD

**Issue by BiancaBauer42** [openshift/openshift-restclient-python#331]
After updating from version 0.8.1 to 0.10.0 I can't use `dyn_client = DynamicClient(k8s_client)` (like shown in the examples) anymore. When calling it, I get the following error:
``AttributeError: module 'os' has no attribute 'getuid'``
Apparently, the init method of the Discoverer class uses `os.getuid` to define default_cachefile_name. Unfortunately, this is only supported for Unix not for Windows.
Is there a way to avoid this error when using Windows?

**Comment by inkitm** [comment]
Same issue.
Any workaround or fix available or we need to downgrade the version?
